name: Deploy and Rollback Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulate Build
        run: echo "Building project..."

      - name: Simulate Tests
        run: echo "Running tests..."

      - name: Deploy
        run: |
          echo "Deploying..."
          mkdir deployment
          echo "Version deployed at $(date)" > deployment/version.txt

      - name: Rollback on Failure
        if: failure()
        run: echo "Rollback triggered!"
