name: Deploy and Rollback Automation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          echo "Building the project..."
          sleep 2
git status

      - name: Deploy Project
        run: |
          echo "Deploying the project..."
          sleep 2

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Deployment failed — rolling back to previous stable version..."